### ISSUE TITLE
[300 SigmaUSD] Vote for update(pool) command

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#26]
**Should be done after #45 is merged.**

To vote for the pool box update as per https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#vote-for-update (with updates introduced in [v2.0a](https://github.com/scalahub/OraclePool/tree/v2/src/main/scala/oraclepool/v2a), e.g reward tokens were moved from the refresh box to the pool box) add a new command line option `--vote-update-pool` with the following parameters:
- new pool box hash (blake2b256);
- height of the update box;

If the ballot token is locked in the existing ballot box (i.e. output of the previous update tx) it should be spent to create the new ballot box.

**Comment by kettlebell** [comment]
I will work on this.

**Comment by kettlebell** [comment]
Hi @greenhat I have a question about this issue:
 
Should the owner of the ballot token have their group element stored in the oracle config? Seems like it since we will need to implement [transfer ballot token](https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#transfer-ballot-token).
 - An idea: we could do away with storing it in the config by scanning for local ballot box as follows:
   - Get all wallet addresses from node `/wallet/addresses` endpoint. For each address `a`, perform a scan for the box with the `ballot_token_id` and the group element of `a`.

What do you reckon? Thanks.

**Comment by greenhat** [comment]
> Hi @greenhat I have a question about this issue:
> 
> Should the owner of the ballot token have their group element stored in the oracle config? Seems like it since we will need to implement [transfer ballot token](https://github.com/ergoplatform/eips/blob/bd7a6098db78d67ac2ca9ada4c09bfe709d5ac03/eip-0023.md#transfer-ballot-token).
> 
>     * An idea: we could do away with storing it in the config by scanning for local ballot box as follows:
>       
>       * Get all wallet addresses from node `/wallet/addresses` endpoint. For each address `a`, perform a scan for the box with the `ballot_token_id` and the group element of `a` in `R4`.
> 
> 
> What do you reckon? Thanks.

I think it's ok to store it in the config. Scanning for it seems way more complex. Let's try a simple solution first. :)

**Comment by kettlebell** [comment]
I'm almost done with this issue but I ran into a problem with the case where we're spending an existing ballot box. I got the following error:
`TxSigningError(ProverError(EvalError(Misc("ByIndex: index Int(0) out of bounds for collection size 0")), 0))`

I tracked it down and the problem originates [in this line of the contract](https://github.com/scalahub/OraclePool/blob/58726e7751b2ff454ce4b3f45315f3cd549c2994/src/main/scala/oraclepool/v2a/Contracts.scala#L190). Now I believe we need to amend the contract because for the `vote for update` command there's only one fixed input (the existing ballot box) as specified in the EIP, and so `INPUTS(1)` has no guarantee to contain any token.

So I amended the contract by removing the line with `val otherTokenId = INPUTS(1).tokens(0)._1` and replacing `update` with:

```scala
val update = INPUTS.size > 1                           &&
             INPUTS(1).tokens.size > 0                 &&
             INPUTS(1).tokens(0)._1 == updateNFT       && // can only update when update box is the 2nd input
             output.R4[GroupElement].get == selfPubKey && // public key is preserved
             output.value >= SELF.value                && // value preserved or increased
             ! (output.R5[Any].isDefined)                 // no more registers; prevents box from being reused as a valid vote 
```
Then the test passes. Am I doing this correctly?

**Comment by greenhat** [comment]
@kettlebell Good call! I agree. 
@scalahub Please check and approve the proposed update to the ballot contract above. The reason for the update is that `val otherTokenId = INPUTS(1).tokens(0)._1` throws on voting, i.e. spending the ballot box without the update box.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
