### ISSUE TITLE
Introduce enum for storing datapoint source names in the oracle config

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/oracle-core#55]
To avoid manual name matching on config load at https://github.com/ergoplatform/oracle-core/blob/fcffd8a1c22900f99511d25f22e1b34ef0fdaf80/core/src/oracle_config.rs#L52-L56

**Comment by SethDusek** [comment]
I have a branch with one design of a DataSource that encapsulates all of the oracles included in oracle-core (NanoErgUsd, NanoAdaUsd, NanoErgXau, etc) [in this branch](https://github.com/SethDusek/oracle-core/tree/datapointsource). You can take a look and if it looks good then I can send a PR

I wasn't able to test out the serialization though since the default template for oracle_config.yaml seems to be panicking on some missing parameters. I'm guessing the template hasn't been updated for oracle v2?

**Comment by greenhat** [comment]
> I have a branch with one design of a DataSource that encapsulates all of the oracles included in oracle-core (NanoErgUsd, NanoAdaUsd, NanoErgXau, etc) [here](https://github.com/SethDusek/oracle-core/tree/datapointsource). You can take a look and if it looks good then I can send a PR

Yes. Please, make a PR.

> 
> I wasn't able to test out the serialization though since the default template for oracle_config.yaml seems to be panicking on some missing parameters. I'm guessing the template hasn't been updated for oracle v2?

Seems so. The config is still in WIP stage although it's pretty close to the finish line.

**Comment by greenhat** [comment]
Done in #66
